######################################################################
# Automatically generated by qmake (2.01a) Wed Mar 22 15:02:08 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += network widgets
FORMS = chatdialog.ui

# Input
HEADERS += netsocket.hh client.hh chatdialog.hh p2pmanager.hh
SOURCES += main.cc netsocket.cc client.cc chatdialog.cc p2pmanager.cc
